stages:
  - token
  - test
  - doc
  - pypi

generate-token:
  stage: token
  image: docker.audeering.com/alpine
  before_script:
    - apk --no-cache add git curl bash
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${GITLAB_USER_LOGIN}/artifactory-tokenizer.git
    - cd artifactory-tokenizer
    - bash get_token.sh "readers,deployers" > ../token.json
  artifacts:
    paths:
      - token.json
    expire_in: 20 mins

.pytest:
  before_script:
    - username=${GITLAB_USER_LOGIN}
    - api_key=$(cat token.json | jq -r '.access_token')
    - export ARTIFACTORY_USERNAME=${username}
    - export ARTIFACTORY_API_KEY=${api_key}
    - export TWINE_USERNAME=${username}
    - export TWINE_PASSWORD=${api_key}
    - python -V
  script:
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - python -m pytest
  dependencies:
    - generate-token

python-3.6:
  extends: .pytest
  stage: test
  image: docker.audeering.com/audeering/python-3.6:latest

python-3.7:
  extends: .pytest
  stage: test
  image: docker.audeering.com/audeering/python-3.7:latest

python-3.8:
  extends: .pytest
  stage: test
  image: docker.audeering.com/audeering/python-3.8:latest

#test-windows-general:  https://gitlab.audeering.com/devops/gitlab-runners/-/issues/67
#  # Based on Python 3.8 by default
#  stage: test
#  tags:
#    - windows
#  script:
#    - pip install -r requirements.txt
#    - pip install -r tests/requirements.txt
#    - python -m pytest

docs:
  extends: .pytest
  stage: test
  image: docker.audeering.com/audeering/python-3.6:latest
  script:
    - pip install -r requirements.txt
    - pip install -r docs/requirements.txt
    - python -m sphinx -W docs/ -d build/doctrees build/html -b html
    - python -m sphinx -W docs/ build/linkcheck -b linkcheck
  artifacts:
    paths:
      - build/

pages:
  stage: doc
  image: docker.audeering.com/alpine
  variables:
    GIT_STRATEGY: none  # disable git fetch
  script:
    - cp -r build/html public
  dependencies:
    - docs
  artifacts:
    paths:
      - public
  only:
    refs:
      - tags

pypi:
  extends: .pytest
  stage: pypi
  image: docker.audeering.com/python:3.6
  variables:
    TWINE_REPOSITORY_URL: https://artifactory.audeering.com/artifactory/api/pypi/pypi
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload --repository local dist/*
  only:
    refs:
      - tags
