name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]

    steps:
    - uses: actions/checkout@v3

    - name: Cache emodb
      uses: actions/cache@v3
      with:
        path: ~/audb
        key: emodb-1.3.0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Prepare Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends --yes libsndfile1 sox
      if: matrix.os == 'ubuntu-latest'

    - name: Install dependencies
      run: |
        python -V
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r docs/requirements.txt
        pip install -r tests/requirements.txt

    - name: Test with pytest
      run: |
        python -m pytest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
      if: matrix.os == 'ubuntu-latest'

    - name: Test building documentation
      run: |
        python -m sphinx docs/ docs/_build/ -b html -W
        # Disbale link check until new release is done
        # python -m sphinx docs/ build/sphinx/html -b linkcheck
      if: matrix.os == 'ubuntu-latest'
